### ISSUE TITLE
Dependency problem in org.apache.poi with XSSFWorkbook

### ISSUE THREAD

**Issue by guillaume-doux** [ObeoNetwork/Bits#3]
The package commons-collections4-4.1 is missing in the dependencies of org.apache.poi.
When trying to instanciate an XSSFWorkbook, a "java.lang.NoClassDefFoundError: org/apache/commons/collections4/ListValuedMap" is thrown.

The import of commons-collections4-4.1 solves the problem.

**Comment by cbrun** [comment]
The build will kick in (see https://travis-ci.org/ObeoNetwork/Bits/builds/253202398) and the corresponding repo (http://obeo-networkaggregation-releases.s3-website-eu-west-1.amazonaws.com/bits/master/thirdparties) will contain the fix in a few minutes, can you confirm that fixes your problem then please ?
